services:
  app:
    build: .
    container_name: app
    entrypoint: >
      sh -c "
        composer update &&
        service cron start &&
        php artisan octane:start  --server=frankenphp  --workers=8  --max-requests=200 --watch
      "
    working_dir: /app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./logs:/var/log

