services:
  app:
    build: .
    container_name: app
    entrypoint: php artisan octane:frankenphp --workers=8 --max-requests=200
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./logs:/var/log

