services:
  app:
    build: .
    container_name: app
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
